use crate::error::ParseError;

/// Generated by `#[derive(Provision)]` for every annotated config struct.
///
/// The trait provides everything the runtime needs: an HTML form page,
/// request-body parsing, and flash-storage round-tripping.
///
/// Users never implement this trait manually — the derive macro handles it.
pub trait ProvisionConfig: Sized {
    /// The complete HTML configuration page, built at compile time.
    const HTML: &'static str;

    /// Parse an `application/x-www-form-urlencoded` POST body into `Self`.
    ///
    /// Takes `&[u8]` to compose directly with [`crate::http::Request::body`].
    fn from_form(body: &[u8]) -> Result<Self, ParseError>;

    /// Serialize `self` into `buf` for flash storage.  Returns the number of
    /// bytes written.
    fn to_bytes(&self, buf: &mut [u8]) -> Result<usize, ParseError>;

    /// Deserialize `Self` from bytes previously written by [`to_bytes`](Self::to_bytes).
    fn from_bytes(buf: &[u8]) -> Result<Self, ParseError>;
}
