//! Internal helpers exposed for code generated by `#[derive(Provision)]`.

/// Minimal `fmt::Write` impl over a `&mut [u8]` for `no_std`.
///
/// Used by the generated `to_bytes` method to format field values without
/// an allocator.
pub struct StringWriter<'a> {
    pub buf: &'a mut [u8],
    pub pos: usize,
}

impl<'a> ::core::fmt::Write for StringWriter<'a> {
    fn write_str(&mut self, s: &str) -> ::core::fmt::Result {
        let bytes = s.as_bytes();
        if self.pos + bytes.len() > self.buf.len() {
            return Err(::core::fmt::Error);
        }
        self.buf[self.pos..self.pos + bytes.len()].copy_from_slice(bytes);
        self.pos += bytes.len();
        Ok(())
    }
}
